### ISSUE TITLE
Delete button not deleting table row

### ISSUE THREAD

**Issue by kamalpreetgrewal** [kamalpreetgrewal/TBMShiftPlanner#1]
On clicking `Delete` button in a table row, the corresponding record is deleted from the database. However, the table view is not updated until the page is refreshed. The record should be deleted from the table too on clicking the button at the same time.

**Comment by douglas19772** [comment]
I think the child component (TableRow) needs to notify the parent component (IndexComponent) about changes in the underlying data, so the parent can rerender properly. 

Maybe this link could help you https://ourcodeworld.com/articles/read/409/how-to-update-parent-state-from-child-component-in-react

I haven't used github before. I'll try to make a proper pull request.

**Comment by kamalpreetgrewal** [comment]
@douglas19772 The link was very helpful. The pull request is perfect and I have merged it. Thank you so much. Got to learn something new from you.
